#!/bin/sh
mkdir -p /tmp/newroot/home/stefano/apt-cache/partial
mkdir -p /tmp/newroot/dev
mkdir -p /tmp/newroot/var/lib/dpkg/tmp.ci
mkdir -p /tmp/newroot/root
touch /tmp/newroot/root/.dpkg.cfg
vumount -t vufs -o cow /tmp/newroot /
rm -rf /var/lib/dpkg/lock-frontend
cp .config/apt/apt.conf /apt.conf
export APT_CONFIG="/apt.conf"
